In [241]:
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [242]:
df = pd.read_csv('../../data/raw/nb_data/1. scraped_data/appartments.csv')

In [243]:
df.head(2)

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."

In [244]:
df.iloc[20:25]

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
20,Tulip Monsella,"3, 4, 5 BHK Apartment in Sector 53, Gurgaon","['Mavens Inn', 'Sanar International Hospital',...","{'Mavens Inn': '350 M', 'Sanar International H...",https://www.99acres.com/tulip-monsella-sector-...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Mini Theatre', 'Swimming Pool', 'Bar/Chill-O..."
21,Krisumi Waterfall Residences,"1, 2, 3, 4 BHK Apartment, 1 RK Studio Apartmen...","['Dwarka Expy', 'Delhi Public School, Sector 8...","{'Dwarka Expy': '6 KM', 'Delhi Public School, ...",https://www.99acres.com/krisumi-waterfall-resi...,"{'1 BHK': {'building_type': 'Apartment', 'area...","['Concierge Service', 'Swimming Pool', 'Bar/Ch..."
22,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
23,M3M Capital,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Dwarka Expy', 'Shivani public school', 'Bagh...","{'Dwarka Expy': '10 m', 'Shivani public school...",https://www.99acres.com/m3m-capital-sector-113...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Lounge', 'Bar/Chill-Out Lou..."
24,Godrej Meridien,"1, 2, 3, 4 BHK Apartment in Sector 106, Gurgaon","['Dwarka Expressway', 'Euro International Scho...","{'Dwarka Expressway': '1.8 Km', 'Euro Internat...",https://www.99acres.com/godrej-meridien-sector...,"{'1 BHK': {'building_type': 'Apartment', 'area...","['Valet Parking', 'Mini Theatre', 'Concierge S..."

In [245]:
df.shape

(247, 7)

In [246]:
df.drop(22, axis=0, inplace=True)

In [247]:
df.shape

(246, 7)

In [248]:
df.iloc[20:25]

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
20,Tulip Monsella,"3, 4, 5 BHK Apartment in Sector 53, Gurgaon","['Mavens Inn', 'Sanar International Hospital',...","{'Mavens Inn': '350 M', 'Sanar International H...",https://www.99acres.com/tulip-monsella-sector-...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Mini Theatre', 'Swimming Pool', 'Bar/Chill-O..."
21,Krisumi Waterfall Residences,"1, 2, 3, 4 BHK Apartment, 1 RK Studio Apartmen...","['Dwarka Expy', 'Delhi Public School, Sector 8...","{'Dwarka Expy': '6 KM', 'Delhi Public School, ...",https://www.99acres.com/krisumi-waterfall-resi...,"{'1 BHK': {'building_type': 'Apartment', 'area...","['Concierge Service', 'Swimming Pool', 'Bar/Ch..."
23,M3M Capital,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Dwarka Expy', 'Shivani public school', 'Bagh...","{'Dwarka Expy': '10 m', 'Shivani public school...",https://www.99acres.com/m3m-capital-sector-113...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Lounge', 'Bar/Chill-Out Lou..."
24,Godrej Meridien,"1, 2, 3, 4 BHK Apartment in Sector 106, Gurgaon","['Dwarka Expressway', 'Euro International Scho...","{'Dwarka Expressway': '1.8 Km', 'Euro Internat...",https://www.99acres.com/godrej-meridien-sector...,"{'1 BHK': {'building_type': 'Apartment', 'area...","['Valet Parking', 'Mini Theatre', 'Concierge S..."
25,La Vida by Tata Housing,"2, 3 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', ""Rion's Hospital"", 'Dwarka E...","{'Bajghera Road': '550 Meter', ""Rion's Hospita...",https://www.99acres.com/la-vida-by-tata-housin...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Mini Theatre', 'Natural Pond', 'Swimming Poo..."

In [249]:
df.iloc[2].NearbyLocations

"['AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56']"

In [250]:
df.iloc[2].LocationAdvantages

"{'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'Rapid Metro Station Sector 56': '3.8 Km', 'De Adventure Park': '6.8 Km', 'Golf Course Ext Rd': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'KIIT College of Engineering Sohna Road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'Indira Gandhi International Airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}"

In [251]:
df.iloc[1].PriceDetails

"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}"

In [252]:
df.iloc[2].TopFacilities

"['Terrace Garden', 'Gazebo', 'Fountain', 'Amphitheatre', 'Party Lawn', 'Basketball Court', 'Badminton Court', 'Yoga/Meditation Area', 'Indoor Games']"

In [253]:
df[['PropertyName','TopFacilities']]['TopFacilities'][0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

In [254]:
def extract_list(s):
    return re.findall(r"'(.*?)'", s)

df['TopFacilities'] = df['TopFacilities'].apply(extract_list)

In [255]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","[Bowling Alley, Mini Theatre, Manicured Garden..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"[Terrace Garden, Gazebo, Fountain, Amphitheatr..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Volley Ball Court, Aerobics Ce..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"[Mini Theatre, Doctor on Call, Concierge Servi..."

In [256]:
df['FacilitiesStr'] = df['TopFacilities'].apply(' '.join)

In [257]:
df['FacilitiesStr'][0]

'Swimming Pool Salon Restaurant Spa Cafeteria Sun Deck 24x7 Security Club House Gated Community'

In [258]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

In [259]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['FacilitiesStr'])

In [260]:
tfidf_matrix.toarray()[0]

array([0.        , 0.        , 0.        , 0.18809342, 0.18809342,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16873099, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27811185, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.17445059, 0.17445059,
       0.15589841, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16355699, 0.29372893, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.18084455, 0.18084455,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17445059, 0.        , 0.24773259, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06440364,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2659983 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12932284, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21010446, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16522746,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25610081, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15177345,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.21412748, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14918792,
       0.29372893, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16355699, 0.16355699, 0.        ,
       0.        , 0.        , 0.06493586, 0.06493586, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [261]:
cosine_sim_facilities = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [262]:
cosine_sim_facilities.shape

(246, 246)

In [263]:
df[['PropertyName','PriceDetails']]['PriceDetails'][1]

"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}"

In [264]:
def recommend_properties(property_name, cosine_sim=cosine_sim_facilities):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim_facilities[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    recommendations_df.sort_values(by='SimilarityScore', )

    # Return the top 10 most similar properties
    return recommendations_df

In [265]:
recommend_properties("DLF The Arbour")

           PropertyName            SimilarityScore
64      Ace Palm Floors   (63, 0.4529382062441955)
217         Yashika 104  (216, 0.4199606322926784)
93       JMS The Nation   (92, 0.4166584649363288)
154       India Rashtra   (153, 0.398954234680194)
0    Smartworld One DXP   (0, 0.38885046199432893)

In [266]:
import pandas as pd
import json

# Load the dataset
df_appartments = pd.read_csv('../../data/raw/nb_data/1. scraped_data/appartments.csv').drop(22)

# Function to parse and extract the required features from the PriceDetails column
def refined_parse_modified_v2(detail_str):
    try:
        details = json.loads(detail_str.replace("'", "\""))
    except:
        return {}

    extracted = {}
    for bhk, detail in details.items():
        # Extract building type
        extracted[f'building type_{bhk}'] = detail.get('building_type')

        # Parsing area details
        area = detail.get('area', '')
        area_parts = area.split('-')
        if len(area_parts) == 1:
            try:
                value = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area low {bhk}'] = value
                extracted[f'area high {bhk}'] = value
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None
        elif len(area_parts) == 2:
            try:
                extracted[f'area low {bhk}'] = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area high {bhk}'] = float(area_parts[1].replace(',', '').replace(' sq.ft.', '').strip())
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None

        # Parsing price details
        price_range = detail.get('price-range', '')
        price_parts = price_range.split('-')
        if len(price_parts) == 2:
            try:
                extracted[f'price low {bhk}'] = float(price_parts[0].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                extracted[f'price high {bhk}'] = float(price_parts[1].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                if 'L' in price_parts[0]:
                    extracted[f'price low {bhk}'] /= 100
                if 'L' in price_parts[1]:
                    extracted[f'price high {bhk}'] /= 100
            except:
                extracted[f'price low {bhk}'] = None
                extracted[f'price high {bhk}'] = None

    return extracted
# Apply the refined parsing and generate the new DataFrame structure
data_refined = []

for _, row in df_appartments.iterrows():
    features = refined_parse_modified_v2(row['PriceDetails'])
    
    # Construct a new row for the transformed dataframe
    new_row = {'PropertyName': row['PropertyName']}
    
    # Populate the new row with extracted features
    for config in ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5 BHK', '6 BHK', '1 RK', 'Land']:
        new_row[f'building type_{config}'] = features.get(f'building type_{config}')
        new_row[f'area low {config}'] = features.get(f'area low {config}')
        new_row[f'area high {config}'] = features.get(f'area high {config}')
        new_row[f'price low {config}'] = features.get(f'price low {config}')
        new_row[f'price high {config}'] = features.get(f'price high {config}')
    
    data_refined.append(new_row)

df_final_refined_v2 = pd.DataFrame(data_refined).set_index('PropertyName')

In [267]:
df_final_refined_v2['building type_Land'] = df_final_refined_v2['building type_Land'].replace({'':'Land'})

In [268]:
df['PriceDetails'][10]

"{'2 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,055 sq.ft.', 'price-range': '₹ 1.05 - 1.5 Cr'}, '3 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,325 - 1,525 sq.ft.', 'price-range': '₹ 1.35 - 1.84 Cr'}}"

In [269]:
df_final_refined_v2

,building type_1 BHK,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,building type_2 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,...,building type_1 RK,area low 1 RK,area high 1 RK,price low 1 RK,price high 1 RK,building type_Land,area low Land,area high Land,price low Land,price high Land
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,None,NaN,NaN,NaN,NaN,Apartment,1370.0,1370.0,2.0000,2.40,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
M3M Crown,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,Land,500.0,4329.0,2.05,41.13
Sobha City,None,NaN,NaN,NaN,NaN,Apartment,1381.0,1692.0,1.5500,3.21,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Signature Global City 93,None,NaN,NaN,NaN,NaN,Independent Floor,981.0,1118.0,0.9301,1.06,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,None,NaN,NaN,NaN,NaN,Apartment,964.0,964.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Pyramid Urban Homes 2,Apartment,335.0,398.0,23.45,0.2786,Apartment,500.0,625.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Satya The Hermitage,None,NaN,NaN,NaN,NaN,Apartment,1450.0,1450.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
BPTP Spacio,None,NaN,NaN,NaN,NaN,Apartment,1000.0,1079.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
SS The Coralwood,None,NaN,NaN,NaN,NaN,Apartment,1320.0,1425.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN

In [270]:
categorical_columns = df_final_refined_v2.select_dtypes(include=['object']).columns.tolist()

In [271]:
categorical_columns

['building type_1 BHK',
 'building type_2 BHK',
 'building type_3 BHK',
 'building type_4 BHK',
 'building type_5 BHK',
 'building type_6 BHK',
 'building type_1 RK',
 'building type_Land']

In [272]:
ohe_df = pd.get_dummies(df_final_refined_v2, columns=categorical_columns, drop_first=True)

In [273]:
ohe_df.fillna(0,inplace=True)

In [274]:
ohe_df

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,0.0,0.0,0.00,0.0000,1370.0,1370.0,2.0000,2.40,1850.0,2050.0,...,False,False,False,False,False,False,False,False,False,False
M3M Crown,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1605.0,2170.0,...,False,False,False,False,False,False,False,False,False,False
Adani Brahma Samsara Vilasa,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1800.0,3150.0,...,False,False,True,False,False,True,False,False,False,False
Sobha City,0.0,0.0,0.00,0.0000,1381.0,1692.0,1.5500,3.21,1711.0,2343.0,...,False,False,False,False,False,False,False,False,False,False
Signature Global City 93,0.0,0.0,0.00,0.0000,981.0,1118.0,0.9301,1.06,1235.0,1530.0,...,True,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.0,0.0,0.00,0.0000,964.0,964.0,0.0000,0.00,1127.0,1127.0,...,False,False,False,False,False,False,False,False,False,False
Pyramid Urban Homes 2,335.0,398.0,23.45,0.2786,500.0,625.0,0.0000,0.00,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
Satya The Hermitage,0.0,0.0,0.00,0.0000,1450.0,1450.0,0.0000,0.00,1991.0,1991.0,...,False,False,False,False,False,False,False,False,False,False
BPTP Spacio,0.0,0.0,0.00,0.0000,1000.0,1079.0,0.0000,0.00,1225.0,1865.0,...,False,False,False,False,False,False,False,False,False,False
SS The Coralwood,0.0,0.0,0.00,0.0000,1320.0,1425.0,0.0000,0.00,1750.0,1890.0,...,False,False,False,False,False,False,False,False,False,False

In [275]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
ohe_df_normalized = pd.DataFrame(scaler.fit_transform(ohe_df), columns=ohe_df.columns, index=ohe_df.index)

In [276]:
ohe_df_normalized.head()

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-0.252266,-0.169584,-0.105197,-0.082332,1.223499,1.020101,-0.173712,1.158423,0.553787,0.370864,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
M3M Crown,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.293086,0.472749,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Adani Brahma Samsara Vilasa,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.500583,1.304803,...,-0.289310,-0.063888,2.683282,-0.063888,-0.171139,3.924283,-0.236208,-0.111111,-0.216353,-0.063888
Sobha City,-0.252266,-0.169584,-0.105197,-0.082332,1.240497,1.470610,-0.198425,1.680336,0.405879,0.619632,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Signature Global City 93,-0.252266,-0.169584,-0.105197,-0.082332,0.622383,0.667529,-0.232468,0.295011,-0.100626,-0.070634,...,3.456497,-0.063888,2.683282,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888

In [277]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity matrix
cosine_sim_price = cosine_similarity(ohe_df_normalized)

In [278]:
cosine_sim_price.shape

(246, 246)

In [279]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_price[ohe_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = ohe_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('M3M Golf Hills')

                PropertyName  SimilarityScore
0    AIPL The Peaceful Homes         0.955462
1         Smartworld One DXP         0.954670
2             Unitech Escape         0.953092
3                M3M Capital         0.951156
4                 BPTP Terra         0.943128
..                       ...              ...
240              Golden Park        -0.522391
241      Satya Merano Greens        -0.523660
242       ROF Normanton Park        -0.525129
243          BPTP Green Oaks        -0.525286
244           JMS The Nation        -0.526287

[245 rows x 2 columns]

In [280]:
df.head(2)

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities,FacilitiesStr
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete...",Swimming Pool Salon Restaurant Spa Cafeteria S...
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","[Bowling Alley, Mini Theatre, Manicured Garden...",Bowling Alley Mini Theatre Manicured Garden Sw...

In [281]:
change_txt = {"Heritage Xperiential Learning, CRPF Rd":"Heritage Xperiential Learning School","AapnoGhar":"Aapno Ghar","Aarvy Healthcare Hospital":"Aarvy Hospital","Aarvy Healthcare Super Speciality":"Aarvy Hospital","Aarvy Healthcare":"Aarvy Hospital","AIPL Business Club Sector 62":"AIPL Business Club","AIPL Business Centre":"AIPL Business Tower","Airia Mall Sector 68":"Airia Mall","IGI Airport":"Indira Gandhi International Airport","Indira Gandhi Intl Airport":"Indira Gandhi International Airport","Indira Gandhi Int. Airport":"Indira Gandhi International Airport","Delhi International Airport":"Indira Gandhi International Airport","International Airport":"Indira Gandhi International Airport","IG International Airport":"Indira Gandhi International Airport","Indira Gandhi Airport":"Indira Gandhi International Airport","IGIA Airport":"Indira Gandhi International Airport","Airport":"Indira Gandhi International Airport","Alpine School":"Alpine Convent School","Aman Hospital & Surgical Centre":"Aman Hospital","Ambience Mall New":"Ambience Mall","Amity University Gurugram":"Amity University","Amity":"Amity University","Apollo":"Apollo Pharmacy","Approved Sector 37 Mero Station":"Sector 37 Mero Station","Appu Ghar Water Park":"Appu Ghar","Aravalli Hill View Point":"Aravalli Hills","Aravali Adventure Hill":"Aravalli Hills","Arc Multi Speciality Hospital":"Arc Hospital","Arc Multi Speciality":"Arc Hospital","Artemis":"Artemis Hospital","Artimis hospital":"Artemis Hospital","Artemis Hospital Gurgaon":"Artemis Hospital","Ascendas OneHub Gurgaon":"Ascendas OneHub Gurgaon Business Park","Badshahpur Sohna Rd Hwy,Sector 48":"Badshapur Sohna Highway","Badshahpur Sohna Hwy":"Badshapur Sohna Highway","Badshahpur Sohna Rd Hwy":"Badshapur Sohna Highway","Badshahpur Sohna Rd Hwy, Sector 68":"Badshapur Sohna Highway","Badshahpur Sohna Rd Hwy, Malibu Town":"Badshapur Sohna Highway","Badshahpur Sohna Rd Hwy, Haryana":"Badshapur Sohna Highway","Badshahpur Sohna Rd Hwy, Rajoria Ngr":"Badshapur Sohna Highway","Badshahpur Sohna Rd Hwy, Raghav Vatika":"Badshapur Sohna Highway","Basai Dhankot":"Basai Dhankot Railway Station","Basai Dhankot Railway Station":"Basai Dhankot Railway Station","Basai Dhancourt Railway Station":"Basai Dhankot Railway Station","BM College of Technology":"BM College of Technology & Mgmt","Cambridge Montessori Preschool":"Cambridge Montessori","Cambridge Pre-School":"Cambridge Montessori","Accenture DDC5":"Candor Techspace","Candor TechSpace, Sector 48":"Candor Techspace","Central Park Flower Valley":"Central Park, Sohna Rd","Central Park Resorts":"Central Park, Sohna Rd","Central Park II Road":"Central Park, Sohna Rd","CK Birla Hospital, Gurgaon":"CK Birla Hospital","Conscient One":"Conscient One Mall","Country Inn":"Country Inn & Suites By Radisson","Country Inn & Suites by Radisson":"Country Inn & Suites By Radisson","Country Inn and Suites by Radisson":"Country Inn & Suites By Radisson","Damdama More":"Damdama Lake","Damdama Lake Rd":"Damdama Lake","De Adventure Park":"De Adventure Amusement Park","Delhi - Jaipur Expressway":"Delhi Jaipur Expressway","Delhi Ajmer Expressway":"Delhi Jaipur Expressway","Delh-Ajmer Expy":"Delhi Jaipur Expressway","Delhi Jaipur Highway":"Delhi Jaipur Expressway","Dharampur Main Road":"Dhanwapur Road","DoubleTree by Hilton Hotel Gurgaon":"DoubleTree by Hilton Hotel","Double Tree by Hilton":"DoubleTree by Hilton Hotel","DPG Degree College":"DPG Institute of Technology","DPGITM Engineering College Sector 34":"DPG Institute of Technology","DPSG Palam Vihar":"DPSG Palam Vihar Gurugram","Dwarka Expy":"Dwarka Expressway","Dwarka Expy, Sector 109":"Dwarka Expressway, Sector 109","Dwarka Expy, Sector 88":"Dwarka Expressway, Sector 88","Dwaraka Expressway":"Dwarka Expressway","Dwarka Expy, Dhanwapur Village":"Dwarka Expressway, Dhanwapur Village","Dwarka expressway":"Dwarka Expressway","Dwarka Expy/Northern Peripheral Rd":"Dwarka Expressway/Northern Peripheral Rd","Dwarka expressway Basai crossing":"Dwarka expressway Basai crossing","Dwarka Expressway Link Road":"Dwarka Expressway Link Road","Dwarka Expy, Block D, New Palam Vihar":"Dwarka Expressway, Block D, New Palam Vihar","Dwarka Sector 21, Metro Station":"Dwarka Sector 21 Metro Station","Dwarka Sector 21":"Dwarka Sector 21 Metro Station","Ektaa Hospitals":"Ektaa Hospital","Ektaa Hospitals  Main Sohna Rd":"Ektaa Hospital","Emerald Plaza":"Emerald Plaza Shopping Mall","Euro Intl School, Sector- 109":"Euro International School, Sector- 109","EuroKids Preschool Suncity":"Euro Kids Preschool Suncity","Euro Intl School, Sector 37D, Gurugram":"Euro International School, Sector 37D","Euro Intl School Sec-51":"Euro International School Sec-51","Euro Int. School":"Euro International School","Euro International School, Sector- 109.":"Euro International School, Sector- 109","Euro Int School, Sector 37D, Gurugram":"Euro International School, Sector 37D, Gurugram","Euro International School, Sec 84":"Euro International School, Sector 84","Faridabad - Gurgaon Road":"Faridabad Gurgaon Road","Faridabad - Gurgaon Rd":"Faridabad Gurgaon Road","Faridabad":"Faridabad Gurgaon Road","Fresco Market":"Frescos","Fun N Food Waterpark":"Fun N Food Water Park","Fun N Food WaterPark":"Fun N Food Water Park","Fun N Food Village":"Fun N Food Water Park","Garhi harsaru railway station Gurgaon":"Garhi Harsaru Junction","GD Goenka High School":"GD Goenka Public School","GD Goenka":"GD Goenka Public School","GD Goenka Signature School":"GD Goenka Public School","GD Goenka School":"GD Goenka Public School","G D Goenka World School":"GD Goenka World School","G D Goenka University":"GD Goenka University","Gd goenka university":"GD Goenka University","GD Goenka University, Gurugram":"GD Goenka University","Genesis Hospital":"Genesis Hospital Sector 84","Global city centre":"Global City Centre Mall","Global City Centre":"Global City Centre Mall","Global Foyer Mall":"Global Foyer Mall,  Palam Vihar","Golden Greens Golf & Resorts":"Golden Greens Golf & Resorts Limited","Golf Course Ext Rd":"Golf Course Extension Road","Golf Course Ext Road":"Golf Course Extension Road","Golf Course Road":"Golf Course Extension Road","Golf Course Extension Rd":"Golf Course Extension Road","Golf Course Extension":"Golf Course Extension Road","Golf Corse Ext. Rd.":"Golf Course Extension Road","Golf Course Extn Road":"Golf Course Extension Road","Golf course extension road":"Golf Course Extension Road","Golf Course Rd":"Golf Course Extension Road","Grand Hyatt":"Grand Hyatt Gurgaon","Green Field School":"Green Field Public School","Gurgaon - Delhi Expy":"Gurgaon - Delhi Expy, Sector 75A","Gurgaon Railway Station":"Gurugram Railway Station","Gurgaon railway station":"Gurugram Railway Station","Gurugram Rd":"Gurugram Road","Gurugram University Kankrola":"Gurugram University","Gurugram University Sector 87":"Gurugram University","HDFC bank ATM":"HDFC Bank ATM","Heritage School":"Heritage Xperiential Learning School","Heritage Intl Xperiential School":"Heritage Xperiential Learning School","Holiday Inn Gurugram Sector 90":"Holiday Inn Express","Holiday Inn Sector 90":"Holiday Inn Express","Holiday Inn Hotel Sector 90":"Holiday Inn Express","Holiday Inn Express Gurugram Sector 50":"Holiday Inn Express","Holiday Inn Express Gurugram":"Holiday Inn Express","Holiday Inn Gurugram":"Holiday Inn Express","Holiday Inn Express Gurugram Sec 50":"Holiday Inn Express","Holiday Inn":"Holiday Inn Express","HP PETROL PUMP Unnamed Rd":"HP PETROL PUMP","Hub 66":"HUB 66","Huda Metro Station":"Huda Metro Station","Huda metro station":"Huda Metro Station","Huda City Centre Metro Station":"Huda Metro Station","Huda City Centre":"Huda Metro Station","Huda Metro Station (Gurugram)":"Huda Metro Station","Huda city center":"Huda Metro Station","HUDA Metro Station":"Huda Metro Station","Huda Metro station":"Huda Metro Station","HUDA Market":"HUDA Market, Sector 14","Hyatt Place":"Hyatt Place Gurgaon Udyog Vihar","Hyatt Regency Gurgaon":"Hyatt Regency Gurugram","Hyatt Regency":"Hyatt Regency Gurugram","Hyatt Regency Hotel":"Hyatt Regency Gurugram","ICICI ATM":"ICICI Bank ATM","IFFCO Chowk":"IFFCO Chowk Metro Station","Iffco Chowk":"IFFCO Chowk Metro Station","Iffco Chowk Metro Station":"IFFCO Chowk Metro Station","iGrow Montessori":"iGrow Montessori Play School","IILM School of Management":"IILM University, Gurugram","IMT Manesar":"Imt Manesar, Gurugram","Imt Manesar":"Imt Manesar, Gurugram","IMT Office Sohna":"IMT Sohna Road","IMT Road":"IMT Sohna Road","IMT Sohna":"IMT Sohna Road","International Tech Park Gurgaon,":"International Tech Park Gurgaon","iON Digital Zone, Gurgaon":"iON Digital Zone (Gurugram)","Iris Broadway Mall":"IRIS Broadway Mall","Iris Broadway Gurugram":"IRIS Broadway Mall","ISKCON":"ISKCON Temple","JMS Marine Square":"JMS Marine Square Mall","Jinga Lala Theme Park Gurgaon Delhi":"Jinaglala Theme Park","K.R. Mangalam University":"K. R. Mangalam University","KFG Sports Club":"KFG sports club Parking","Kidzee":"Kidzee Sec-93","KIIT College of Engineering Sohna Road":"KIIT College of Engineering","KIIT College":"KIIT College of Engineering","KR Mangalam University":"K. R. Mangalam University","KR Mangalam University Sohna":"K. R. Mangalam University","KR Mangalam":"K. R. Mangalam University","Kunskapsskolan School":"Kunskapsskolan International","Lemon Tree Hotel, Sohna Road":"Lemon Tree Hotel","Lemon Tree Hotel Sector 60":"Lemon Tree Hotel","Lemon Tree Hotel,":"Lemon Tree Hotel","Lotus Valley Intl School, Gurgaon":"Lotus Valley International School","Lotus Valley School":"Lotus Valley International School","M3m 65th Avenue Mall":"M3M Cosmopolitan Mall","M3M Cosmopolitan":"M3M Cosmopolitan Mall","M3M IFC":"M3M International Financial Center (IFC)","Manipal Hospital":"Manipal Hospital, Gurugram","Manipal Hospital, Palam Vihar":"Manipal Hospital, Gurugram","Matrikiran School":"Matrikiran High School","Mavens Inn":"Mavens Orange - Hotel","McDonald's India 24 Hours":"McDonald's India","Medanta -The Medicity":"Medanta Hospital","Medanta-The Medicity":"Medanta Hospital","Medanta The Medicity":"Medanta Hospital","Medanta Dialysis Center":"Medanta Hospital","Medanta - The Medicity":"Medanta Hospital","Mehrauli-Gurgaon Rd":"Mehrauli-Gurgaon Road","MG Road":"MG Road Metro Station","Minda Industries Nawada Fatehpur":"Minda Industries Limited","Minda Industries  Corporate Office":"Minda Industries Limited","Miracles Apollo Cradle Hospital":"Miracles Apollo Hospital","Miracles Apollo Cradle":"Miracles Apollo Hospital","Miracles Apollo Cradle Spectra Hospital":"Miracles Apollo Hospital","Miracles Apollo Cradle/Spectra Hospital":"Miracles Apollo Hospital","Miracles Apollo Cradle / Spectra":"Miracles Apollo Hospital","Miracles Apollo Cradle /Spectra Hospital":"Miracles Apollo Hospital","Mount Olympus Junior School":"Mount Olympus School, Sec 79","Nakhrola Stadium":"Nakhrola Stadium Sector 81A","Narayana Junior College":"Narayana e Techno School","Narayana E Techno":"Narayana e Techno School","Narayana e-Techno School - Manesar":"Narayana e Techno School","National Highway  48":"National Highway 48","National Highway-48":"National Highway 48","National Tennis Academy":"National Tennis Academy Sector 98","NH 08":"National Highway 8","NH48":"National Highway 48","NH 48":"National Highway 48","NH -8":"National Highway 8","NH8":"National Highway 8","NH 248A":"National Highway 248A","NH-8 Delhi Jaipur Highway":"National Highway 8","NH-8":"National Highway 8","NH 352W, Pataudi":"National Highway 352W, Pataudi","NH 148A":"National Highway 148A","NH-8, IMT Manesar":"National Highway 8","NH 352W":"National Highway 352W","NH-8, Imt Manesar":"National Highway 8","NH-48":"National Highway 48","NH-8 IMT Manesar":"National Highway 8","NH 48 Gurugram":"National Highway 48","NH 8, Sector 15 Part 2":"National Highway 8","NH 48, Sector 78":"National Highway 48","NH 248 A":"National Highway 248A","NH 248":"National Highway 248A","NH 8":"National Highway 8","NH248A":"National Highway 248A","Omaxe Gurgaon Mall":"Omex City Centre Mall","Omaxe City Centre":"Omex City Centre Mall","Omaxe Celebration Mall":"Omex City Centre Mall","Omaxe City Centre Mall":"Omex City Centre Mall","OMAXE Gurgaon Mall":"Omex City Centre Mall","Palam Vihar Halt":"Palam Vihar Halt Railway Station","Paras Hospitals, Gurgaon":"Paras Hospital","Paras Hospitals":"Paras Hospital","Paras Trinity Mall Sector 63":"Paras Trinity Shopping Mall","Paras Trinity Mall":"Paras Trinity Shopping Mall","Paras Trinity":"Paras Trinity Shopping Mall","Park Hospital, Palam Vihar":"Park Hospital","Park Dr, DLF Phase 5":"Park Hospital","Park Inn":"Park Inn, Gurgaon","Pataudi Rd, Sector 95B":"Pataudi Road","Pataudi road":"Pataudi Road","Pataudi Rd":"Pataudi Road","Pathways":"Pathways School Gurgaon","Patil Station":"Patli Railway Station","Pranavananda Int. School":"Pranavananda International School","Prime Scholars Int. School":"Prime Scholars International School","Proposed Metro corridor":"Proposed Metro Station","Propose Metro Station":"Proposed Metro Station","PVR Drive in Theatre":"PVR Drive In Cinema","PVR Drive In Theater":"PVR Drive In Cinema","Radisson Hotel":"Radisson Hotel Sohna Road","Radisson Hotel Gurugram Sohna Road":"Radisson Hotel Sohna Road","Radisson Hotel Gurugram":"Radisson Hotel Sohna Road","Rajiv Chowk":"Rajiv Chowk - Sohna Highway","Rapid Metro Station Sector 56":"Rapid Metro Sector 55-56","Rapid Metro Sector 56":"Rapid Metro Sector 55-56","Rapid Metro Station Sector 55 56":"Rapid Metro Sector 55-56","Rion's Hospital":"Rions Hospital","Royal Institute Of Science":"Royal Institute Of Science & Management","Royal Institute Of Science and Mgt":"Royal Institute Of Science & Management","RPS International School":"RPS International School Sector 89","Sanjivani Hospital":"Sanjeevani Hospital","Sanjeevani Hospital - Child Specialist":"Sanjeevani Hospital","Sapphire 83 Mall":"Sapphire 83 Mall Sector 83","Sapphire 83":"Sapphire 83 Mall Sector 83","Sapphire Mall":"Sapphire 83 Mall Sector 83","Sapphire 93 Mall":"Sapphire 83 Mall Sector 83","Savoy Suites":"Savoy Suites, Manesar","SCC Rooftop Drive-In":"SCC Drive-In Cinema","Scottish High International School":"Scottish International School","Sealdah":"Sealdah Railway Station","Sector 42-43":"Sector 42/43 Bus Stand","Sector 42-43 Rapid Metro":"Sector 42-43 Rapid Metro Station","Sector 42-43 Metro Station":"Sector 42-43 Rapid Metro Station","Sector 53-54 Metro Station":"Sector 53-54 Metro Station","Sector 54 Chowk Metro Station":"Sector 53-54 Metro Station","Sector 53-54 Rapid Metro":"Sector 53-54 Metro Station","Sector 53 Metro Station":"Sector 53-54 Metro Station","Sector 53-54":"Sector 53-54 Metro Station","Sector 53/54 Metro Station":"Sector 53-54 Metro Station","Sector 55/56 Metro Station":"Sector 55-56 Metro Station","Sector 55 Metro Station":"Sector 55-56 Metro Station","Sector 55-56 Metro station":"Sector 55-56 Metro Station","Sector 55-56 metro":"Sector 55-56 Metro Station","Sector 55-56 Rapid Metro Station":"Sector 55-56 Metro Station","Sector 55-56 Metro":"Sector 55-56 Metro Station","Sector 55-56 Rapid Metro":"Sector 55-56 Metro Station","Sector 55-56 rapid metro station":"Sector 55-56 Metro Station","Sector 55-56 metro station":"Sector 55-56 Metro Station","SGT Hospital 1":"SGT Medical College","Shoppers Stop":"Shoppers Stop Sector 54","Signature Advanced Hospital":"Signature Hospital","Silver Streak Multi Speciality":"Silver Streak Multi Speciality Hospital","Silver Streak Hospital":"Silver Streak Multi Speciality Hospital","SkyJumper Trampoline Park":"SkyJumper Trampoline Park Gurgaon","Sohna Rd":"Sohna Road","Southern Peripheral Rd":"Southern Peripheral Road","Southern Peripheral Rd, Gurugram":"Southern Peripheral Road","Southern Peripheral Rd, Dhani":"Southern Peripheral Road","Southern Periphery Road":"Southern Peripheral Road","Spaze Itech Park":"Spaze Business Park","SS Omnia, Sector 86":"SS Omnia Mall","St. Xavier's High School":"St Xavier High School","St. Xavier's School":"St Xavier High School","Suncity School":"Suncity School Gurgaon","Suncity School, Sector 37D":"Suncity School Gurgaon","Suncity Market":"Suncity Shopping Complex","Surajgarh Gurgaon, Golf Course Ext Rd":"Surajgarh Gurgaon","Swastik Hospital Sec 66":"Swastik Multispeciality Hospital","Swastik Hospital":"Swastik Multispeciality Hospital","Taj Hotel & Family Restaurant":"Taj City Centre Gurugram","Taj":"Taj City Centre Gurugram","Taj City Centre Hotel":"Taj City Centre Gurugram","Tau DeviLal Sports Complex":"Tau Devi Lal Sports Complex","The Hive":"The Hive Shopping Mall","The Millenium School":"The Millennium School","The Oberoi":"The Oberoi, Gurgaon","The Oberoi Gurgaon":"The Oberoi, Gurgaon","The Signature Advanced Super Speciality":"The Signature Super Speciality Hospital","The Westin Hotel":"The Westin Hotel Gurgaon","The Westin Gurgaon":"The Westin Hotel Gurgaon","Vardaan Hospital":"Vardaan Hospital & Trauma Centre","Vardaan hospital and trauma centre":"Vardaan Hospital & Trauma Centre","Vardaan Hospital and Trauma Centre":"Vardaan Hospital & Trauma Centre","Vatika Business Centre":"Vatika Business Park Sector 49","Vatika Business Park":"Vatika Business Park Sector 49","VATIKA BUSINESS PARK Sohna Rd":"Vatika Business Park Sector 49","Vatika City Centre":"Vatika City Centre Mall","Vatika Town Square-INXT":"Vatika Town Square-INXT Mall","Vatika Town Square":"Vatika Town Square-INXT Mall","Vega Schools NH-8":"Vega Schools Sector 48","Vega School":"Vega Schools Sector 48","Vipul Trade Business Centre":"Vipul Trade Centre","Vivanta Dwarka New Delhi":"Vivanta New Delhi, Dwarka","Western Peripheral Expy, Gurugram":"Western Peripheral Expressway","WorldMark Gurgaon":"WorldMark Gurgaon, Maidawas Rd","Bharat Petroleum Petrol Pump":"Bharat Petrol Pump","CANARA BANK":"Canara Bank","Delhi Public School":"DPS International School","DPS International Edge":"DPS International School","DPS":"DPS International School"}

In [282]:
def distance_to_meters(distance_str):
    try:
        if 'Km' in distance_str or 'KM' in distance_str:
            return float(distance_str.split()[0]) * 1000
        elif 'Meter' in distance_str or 'meter' in distance_str:
            return float(distance_str.split()[0])
        else:
            return None
    except:
        return None

In [283]:
# Function to replace keys in the dictionary string
def replace_keys(dict_str, replacements):
    dict_obj = ast.literal_eval(dict_str)
    updated_dict = {}
    for location, distance in dict_obj.items():
        for old_value, new_value in replacements.items():
            location = location.replace(old_value, new_value)
        updated_dict[location] = distance
    return str(updated_dict)

In [284]:
df['LocationAdvantages'][4]

"{'Pranavananda Int. School': '450 m', 'DLF Site central office': '1.2 Km', 'Holiday Inn Gurugram Sector 90': '2 Km', 'Krishna Hospital': '2.3 Km', 'Royal Institute Of Science': '2.4 Km', 'Sapphire 83 Mall': '6.3 Km', 'NH48': '6.9 Km', 'Garhi Harsaru Junction': '7.2 Km', 'Manesar Golf Course': '7.3 Km', 'AapnoGhar': '9.6 Km', 'IGI Airport': '31 Km'}"

In [285]:
# Apply the function to the DataFrame
df['LocationAdvantages'] = df['LocationAdvantages'].apply(lambda x: replace_keys(x, change_txt))

In [286]:
df['LocationAdvantages'][4]

"{'Pranavananda International School': '450 m', 'DLF Site central office': '1.2 Km', 'Holiday Inn Express Express': '2 Km', 'Krishna Hospital': '2.3 Km', 'Royal Institute Of Science & Management': '2.4 Km', 'Sapphire 83 Mall Sector 83 Mall Sector 83': '6.3 Km', 'National Highway 48': '6.9 Km', 'Garhi Harsaru Junction': '7.2 Km', 'Manesar Golf Course': '7.3 Km', 'Aapno Ghar': '9.6 Km', 'Indira Gandhi Indira Gandhi International Indira Gandhi International Airport': '31 Km'}"

In [287]:
import ast
# Extract distances for each location
location_matrix = {}
for index, row in df.iterrows():
    distances = {}
    for location, distance in ast.literal_eval(row['LocationAdvantages']).items():
        for old_value, new_value in change_txt.items():
            location.replace(old_value, new_value)
        distances[location] = distance_to_meters(distance)
    location_matrix[index] = distances

# Convert the dictionary to a dataframe
location_df = pd.DataFrame.from_dict(location_matrix, orient='index')

# Display the first few rows
location_df.head()

,Bajghera Road,Palam Vihar Halt Railway Station,DPS International SchoolG Palam Vihar Gurugram,Park Hospital,Gurugram Railway Station,The NorthCap University,Dwarka Expressway,Hyatt Place Gurgaon Udyog Vihar Gurgaon Udyog Vihar,Dwarka Sector 21 Metro Station Metro Station,Pacific D21 Mall,...,Sector 102 Dhankot,Shri Hanuman Ji Mandir,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,Holiday Inn Express,Sector 84 Road,Skyview Corporate Park
0,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,550.0,NaN,NaN,NaN,NaN,6700.0,3800.0,NaN,NaN,7500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,5300.0,NaN,NaN,NaN,2500.0,8800.0,700.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,1500.0,NaN,NaN,NaN,6500.0,6700.0,5100.0,NaN,NaN,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,1400.0,NaN,4400.0,NaN,NaN,8100.0,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [288]:
location_df.columns[10:50]

Index(['Indira Gandhi Indira Gandhi International Indira Gandhi International Airport',
       'Hamoni Golf Camp', 'Fun N Food Water Park', 'Candor Techspace',
       'DPS International SchoolG Palam Vihar Gurugram Gurugram',
       'Palam Vihar Halt Railway Station Railway Station',
       'Tau Devi Lal Sports Complex', 'Hyatt Place Gurgaon Udyog Vihar',
       'Altrade Business Centre', 'AIPL Business Club',
       'Heritage Xperiential Learning School', 'CK Birla Hospital',
       'Paras Trinity Shopping Mall Shopping Mall', 'Rapid Metro Sector 55-56',
       'De Adventure Amusement Park', 'Golf Course Extension Road Road',
       'DoubleTree by Hilton Hotel',
       'KIIT College of Engineering of Engineering', 'Mehrauli-Gurgaon Road',
       'Nirvana Rd', 'TERI Golf Course', 'The Shikshiyan School', 'WTC Plaza',
       'Luxus Haritma Resort', 'BSF Golf Course', 'Rions Hospital', 'Gurgaon',
       'Dwarka Sector 21 Metro Station', 'Nehru Stadium', 'Vasant Kunj',
       'Pranavananda International School', 'DLF Site central office',
       'Holiday Inn Express Express', 'Krishna Hospital',
       'Royal Institute Of Science & Management',
       'Sapphire 83 Mall Sector 83 Mall Sector 83', 'National Highway 48',
       'Garhi Harsaru Junction', 'Manesar Golf Course', 'Aapno Ghar'],
      dtype='object')

In [289]:
location_df.index = df.PropertyName

In [290]:
location_df.head()

,Bajghera Road,Palam Vihar Halt Railway Station,DPS International SchoolG Palam Vihar Gurugram,Park Hospital,Gurugram Railway Station,The NorthCap University,Dwarka Expressway,Hyatt Place Gurgaon Udyog Vihar Gurgaon Udyog Vihar,Dwarka Sector 21 Metro Station Metro Station,Pacific D21 Mall,...,Sector 102 Dhankot,Shri Hanuman Ji Mandir,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,Holiday Inn Express,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
M3M Crown,550.0,NaN,NaN,NaN,NaN,6700.0,3800.0,NaN,NaN,7500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,5300.0,NaN,NaN,NaN,2500.0,8800.0,700.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sobha City,1500.0,NaN,NaN,NaN,6500.0,6700.0,5100.0,NaN,NaN,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Signature Global City 93,NaN,NaN,NaN,1400.0,NaN,4400.0,NaN,NaN,8100.0,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [291]:
location_df.fillna(54000,inplace=True)

In [292]:
location_df

,Bajghera Road,Palam Vihar Halt Railway Station,DPS International SchoolG Palam Vihar Gurugram,Park Hospital,Gurugram Railway Station,The NorthCap University,Dwarka Expressway,Hyatt Place Gurgaon Udyog Vihar Gurgaon Udyog Vihar,Dwarka Sector 21 Metro Station Metro Station,Pacific D21 Mall,...,Sector 102 Dhankot,Shri Hanuman Ji Mandir,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,Holiday Inn Express,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Crown,550.0,54000.0,54000.0,54000.0,54000.0,6700.0,3800.0,54000.0,54000.0,7500.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Adani Brahma Samsara Vilasa,5300.0,54000.0,54000.0,54000.0,2500.0,8800.0,700.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Sobha City,1500.0,54000.0,54000.0,54000.0,6500.0,6700.0,5100.0,54000.0,54000.0,8200.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Signature Global City 93,54000.0,54000.0,54000.0,1400.0,54000.0,4400.0,54000.0,54000.0,8100.0,8200.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Pyramid Urban Homes 2,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Satya The Hermitage,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
BPTP Spacio,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
SS The Coralwood,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0

In [293]:
from sklearn.preprocessing import StandardScaler
# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
location_df_normalized = pd.DataFrame(scaler.fit_transform(location_df), columns=location_df.columns, index=location_df.index)

In [294]:
location_df_normalized

,Bajghera Road,Palam Vihar Halt Railway Station,DPS International SchoolG Palam Vihar Gurugram,Park Hospital,Gurugram Railway Station,The NorthCap University,Dwarka Expressway,Hyatt Place Gurgaon Udyog Vihar Gurgaon Udyog Vihar,Dwarka Sector 21 Metro Station Metro Station,Pacific D21 Mall,...,Sector 102 Dhankot,Shri Hanuman Ji Mandir,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,Holiday Inn Express,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-7.960979,-15.652476,-15.652476,-2.924260,-2.835212,-3.147217,-1.868216,-10.231739,-6.159026,-6.023233,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
M3M Crown,-7.998993,0.063888,0.063888,0.350525,0.382826,-3.054053,-1.748278,0.090308,0.171052,-6.009941,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Adani Brahma Samsara Vilasa,-7.276720,0.063888,0.063888,0.350525,-2.992509,-2.903557,-1.891281,0.090308,0.171052,0.171073,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Sobha City,-7.854539,0.063888,0.063888,0.350525,-2.730347,-3.054053,-1.688309,0.090308,0.171052,-5.916893,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Signature Global City 93,0.128476,0.063888,0.063888,-3.033634,0.382826,-3.218882,0.567458,0.090308,-6.037294,-5.916893,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.128476,0.063888,0.063888,0.350525,0.382826,0.335688,0.567458,0.090308,0.171052,0.171073,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Pyramid Urban Homes 2,0.128476,0.063888,0.063888,0.350525,0.382826,0.335688,0.567458,0.090308,0.171052,0.171073,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Satya The Hermitage,0.128476,0.063888,0.063888,0.350525,0.382826,0.335688,0.567458,0.090308,0.171052,0.171073,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
BPTP Spacio,0.128476,0.063888,0.063888,0.350525,0.382826,0.335688,0.567458,0.090308,0.171052,0.171073,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
SS The Coralwood,0.128476,0.063888,0.063888,0.350525,0.382826,0.335688,0.567458,0.090308,0.171052,0.171073,...,0.0,0.0,0.0,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888

In [295]:
cosine_sim_location = cosine_similarity(location_df_normalized)

In [296]:
cosine_sim_location.shape

(246, 246)

In [297]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    cosine_sim_matrix = 30*cosine_sim_facilities + 20*cosine_sim_price + 8*cosine_sim_location
    # cosine_sim_matrix = cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('Ireo Victory Valley')

                   PropertyName  SimilarityScore
0            Ambience Creacions        35.747658
1        Pioneer Urban Presidia        27.817959
2                Tulip Monsella        26.570549
3                 DLF The Crest        23.775467
4                 Pioneer Araya        23.279294
..                          ...              ...
240  Rishali Luxe Residency 112       -14.770934
241              JMS The Nation       -14.946540
242               Ireo Savannah       -14.995231
243               Corona Greens       -15.044021
244           Vatika Aspiration       -15.788587

[245 rows x 2 columns]

In [298]:
(3*cosine_sim_facilities + 5*cosine_sim_price + 6*cosine_sim_location).shape

(246, 246)

In [299]:
import joblib

joblib.dump(location_df, '../../app/datasets/location_df.joblib')

['../../app/datasets/location_df.joblib']

In [300]:
joblib.dump(cosine_sim_facilities, '../../app/datasets/cosine_sim_facilities.joblib')
joblib.dump(cosine_sim_price, '../../app/datasets/cosine_sim_price.joblib')
joblib.dump(cosine_sim_location, '../../app/datasets/cosine_sim_location.joblib')

['../../app/datasets/cosine_sim_location.joblib']